'use strict';
const $ = (id) => document.getElementById(id);
const ui = Object.fromEntries(['fileInput','dropzone','trackName','trackDetail','currentTime','duration','seek','play','previous','next','speed','speedValue','intensity','intensityValue','reverb','reverbValue','bass','bassValue','clockwise','counterclockwise','export','status','trackList','trackCount','disc','orbitDot'].map(id => [id, $(id)]));
const presets = {classic:{speed:8,intensity:80,reverb:18,bass:20},slow:{speed:16,intensity:75,reverb:20,bass:15},deep:{speed:11,intensity:100,reverb:35,bass:65},fast:{speed:4,intensity:85,reverb:14,bass:25}};
let context, tracks=[], selected=-1, source=null, activeGraph=null, startedAt=0, pausedAt=0, playing=false, direction=1, rendered=null, rendering=false, frame=0;
const status = (message) => { ui.status.textContent=message; };
const time = (seconds) => { const n=Math.max(0,Math.floor(seconds||0)); return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`; };
const settings = () => ({speed:+ui.speed.value,intensity:+ui.intensity.value/100,reverb:+ui.reverb.value/100,bass:+ui.bass.value/100,direction});
function updateValues(){ui.speedValue.value=`${ui.speed.value} sec`;ui.intensityValue.value=`${ui.intensity.value}%`;ui.reverbValue.value=`${ui.reverb.value}%`;ui.bassValue.value=`${ui.bass.value}%`}
function invalidate(){rendered=null;ui.export.textContent='Export 8D audio ↗';ui.export.disabled=selected<0 || rendering}
function setPreset(key){const p=presets[key];for(const name of ['speed','intensity','reverb','bass'])ui[name].value=p[name];document.querySelectorAll('.preset').forEach(b=>b.classList.toggle('active',b.dataset.preset===key));updateValues();invalidate();if(playing){const pos=getPosition();stop(false);pausedAt=pos;play()}}
function orbitPosition(t,s){return Math.sin((2*Math.PI*t/s.speed)*s.direction)}
function channelLevels(t,s){const pos=orbitPosition(t,s);const pan=pos*s.intensity;return [Math.sqrt((1-pan)/2),Math.sqrt((1+pan)/2)]}
function createGraph(ctx, output, s){
 const mono=ctx.createGain();mono.gain.value=.72;
 const bass=ctx.createBiquadFilter();bass.type='lowshelf';bass.frequency.value=170;bass.gain.value=s.bass*11;mono.connect(bass);
 const left=ctx.createGain(),right=ctx.createGain(),merger=ctx.createChannelMerger(2);
 bass.connect(left);bass.connect(right);left.connect(merger,0,0);right.connect(merger,0,1);
 const delay=ctx.createDelay(1);delay.delayTime.value=.19;const feedback=ctx.createGain();feedback.gain.value=.19;const wet=ctx.createGain();wet.gain.value=s.reverb*.85;const tone=ctx.createBiquadFilter();tone.type='lowpass';tone.frequency.value=3600;
 bass.connect(delay);delay.connect(tone);tone.connect(feedback);feedback.connect(delay);tone.connect(wet);wet.connect(merger,0,0);wet.connect(merger,0,1);
 merger.connect(output);return {input:mono,left,right,bass,wet,feedback,dispose(){for(const node of [mono,bass,left,right,merger,delay,feedback,wet,tone])node.disconnect()}};
}
function syncGraph(){if(!activeGraph)return;const s=settings();activeGraph.bass.gain.setTargetAtTime(s.bass*11,context.currentTime,.035);activeGraph.wet.gain.setTargetAtTime(s.reverb*.85,context.currentTime,.035)}
function getPosition(){return playing ? Math.min(tracks[selected].buffer.duration,pausedAt+context.currentTime-startedAt) : pausedAt}
function paint(){if(selected>=0){const pos=getPosition(),duration=tracks[selected].buffer.duration;ui.currentTime.textContent=time(pos);ui.seek.value=duration ? Math.round(pos/duration*1000) : 0;const s=settings();const angle=(pos/s.speed)*360*s.direction;ui.orbitDot.style.transform=`translate(-50%,-50%) rotate(${angle}deg) translateX(var(--orbit-radius, 148px))`;ui.disc.style.transform=`rotate(${playing ? angle*1.4 : angle}deg)`;if(playing&&pos>=duration-.025){stop(false);pausedAt=0;paint();return}}if(playing)frame=requestAnimationFrame(paint)}
function stop(keepPosition=true){if(playing&&keepPosition)pausedAt=getPosition();playing=false;if(source){source.onended=null;try{source.stop()}catch{}source.disconnect();source=null}activeGraph?.dispose();activeGraph=null;ui.play.textContent='▶';ui.play.setAttribute('aria-label','Play');cancelAnimationFrame(frame)}
async function play(){if(selected<0)return;if(!context)context=new (window.AudioContext||window.webkitAudioContext)();await context.resume();if(playing){stop();return}const track=tracks[selected];if(pausedAt>=track.buffer.duration)pausedAt=0;source=context.createBufferSource();source.buffer=track.buffer;const s=settings();activeGraph=createGraph(context,context.destination,s);startedAt=context.currentTime;const [l,r]=channelLevels(pausedAt,s);activeGraph.left.gain.value=l;activeGraph.right.gain.value=r;
 // AudioParam automation keeps the moving sound smooth even when the page is not repainting.
 const interval=.035, horizon=track.buffer.duration-pausedAt;for(let delta=0;delta<=horizon+.05;delta+=interval){const [lv,rv]=channelLevels(pausedAt+delta,s);activeGraph.left.gain.linearRampToValueAtTime(lv,startedAt+delta);activeGraph.right.gain.linearRampToValueAtTime(rv,startedAt+delta)}
 source.connect(activeGraph.input);
 source.start(0,pausedAt);playing=true;ui.play.textContent='Ⅱ';ui.play.setAttribute('aria-label','Pause');paint();}
function select(index){stop(false);selected=index;pausedAt=0;const track=tracks[index];ui.trackName.textContent=track.name;ui.trackDetail.textContent=track.file.type || 'Audio file';ui.duration.textContent=time(track.buffer.duration);ui.seek.disabled=false;ui.play.disabled=false;ui.previous.disabled=tracks.length<2;ui.next.disabled=tracks.length<2;invalidate();ui.trackCount.textContent=`${tracks.length} ${tracks.length===1?'track':'tracks'}`;ui.trackList.replaceChildren(...tracks.map((t,i)=>{const b=document.createElement('button');b.className=`track-row${i===selected?' active':''}`;b.type='button';b.innerHTML='<span class="track-icon" aria-hidden="true">♫</span><span class="name"></span><span class="length"></span>';b.querySelector('.name').textContent=t.name;b.querySelector('.length').textContent=time(t.buffer.duration);b.addEventListener('click',()=>select(i));return b}));paint();status('Ready to preview. Adjust the sound, then export.');}
async function addFiles(fileList){const files=Array.from(fileList||[]);if(!files.length)return;status(`Loading ${files.length} ${files.length===1?'file':'files'}…`);ui.fileInput.value='';if(!context)context=new (window.AudioContext||window.webkitAudioContext)();let added=0,failed=[];for(const file of files){try{const buffer=await context.decodeAudioData(await file.arrayBuffer());if(!buffer.duration||!Number.isFinite(buffer.duration))throw Error('empty audio');tracks.push({file,name:file.name.replace(/\.[^.]+$/,''),buffer});added++;}catch{failed.push(file.name)}}if(added)select(tracks.length-added);if(failed.length)status(`Could not open: ${failed.join(', ')}. Try MP3, M4A, or WAV.`)}
function encodeWav(buffer){const channels=2, samples=buffer.length,bytes=44+samples*channels*2;const raw=new ArrayBuffer(bytes),view=new DataView(raw);const word=(offset,text)=>{for(let i=0;i<text.length;i++)view.setUint8(offset+i,text.charCodeAt(i))};word(0,'RIFF');view.setUint32(4,bytes-8,true);word(8,'WAVE');word(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels,true);view.setUint32(24,buffer.sampleRate,true);view.setUint32(28,buffer.sampleRate*channels*2,true);view.setUint16(32,channels*2,true);view.setUint16(34,16,true);word(36,'data');view.setUint32(40,bytes-44,true);const l=buffer.getChannelData(0),r=buffer.getChannelData(1);for(let i=0,p=44;i<samples;i++){for(const sample of [l[i],r[i]]){const n=Math.max(-1,Math.min(1,sample));view.setInt16(p,n<0?n*32768:n*32767,true);p+=2}}return new Blob([raw],{type:'audio/wav'})}
async function save(){if(!rendered)return;const {file,blob}=rendered;try{if(navigator.canShare?.({files:[file]})&&navigator.share){await navigator.share({files:[file],title:file.name});status('Choose Save to Files in the share sheet.');return}}catch(e){if(e.name==='AbortError')return}const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=file.name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);status('WAV download started. On iPhone, open the download and share it to Files if needed.')}
async function exportAudio(){if(rendered){await save();return}if(selected<0||rendering)return;const track=tracks[selected],s=settings();if(track.buffer.duration>600){status('This version supports tracks up to 10 minutes to protect phone memory.');return}rendering=true;ui.export.disabled=true;ui.export.textContent='Rendering on this device…';status('Converting audio locally. Keep this page open until it finishes.');try{const sampleRate=Math.min(track.buffer.sampleRate,44100);const length=Math.ceil((track.buffer.duration+.6)*sampleRate);const offline=new OfflineAudioContext(2,length,sampleRate);const input=offline.createBufferSource();input.buffer=track.buffer;const graph=createGraph(offline,offline.destination,s);input.connect(graph.input);for(let t=0;t<=track.buffer.duration+.05;t+=.035){const [l,r]=channelLevels(t,s);graph.left.gain.linearRampToValueAtTime(l,t);graph.right.gain.linearRampToValueAtTime(r,t)}input.start(0);const buffer=await offline.startRendering();const blob=encodeWav(buffer);const name=`${track.name} - 8D.wav`;rendered={blob,file:new File([blob],name,{type:'audio/wav'})};ui.export.textContent='Save / share WAV ↗';status(`Ready: ${name} (${(blob.size/1048576).toFixed(1)} MB). Tap to save or share.`)}catch(e){console.error(e);status('Conversion failed. Try a shorter audio file or close other apps to free memory.');ui.export.textContent='Export 8D audio ↗'}finally{rendering=false;ui.export.disabled=false}}
ui.fileInput.addEventListener('change',e=>addFiles(e.target.files));for(const event of ['dragenter','dragover'])ui.dropzone.addEventListener(event,e=>{e.preventDefault();ui.dropzone.classList.add('dragging')});for(const event of ['dragleave','drop'])ui.dropzone.addEventListener(event,e=>{e.preventDefault();ui.dropzone.classList.remove('dragging')});ui.dropzone.addEventListener('drop',e=>addFiles(e.dataTransfer.files));ui.play.addEventListener('click',()=>play().catch(()=>status('Could not start playback. Tap Play again.')));ui.previous.addEventListener('click',()=>select((selected-1+tracks.length)%tracks.length));ui.next.addEventListener('click',()=>select((selected+1)%tracks.length));ui.seek.addEventListener('input',()=>{if(selected<0)return;const resume=playing;stop(false);pausedAt=tracks[selected].buffer.duration*ui.seek.value/1000;paint();if(resume)play()});document.querySelectorAll('.preset').forEach(b=>b.addEventListener('click',()=>setPreset(b.dataset.preset)));for(const name of ['speed','intensity','reverb','bass'])ui[name].addEventListener('input',()=>{document.querySelectorAll('.preset').forEach(b=>b.classList.remove('active'));updateValues();invalidate();syncGraph();if(playing&&(name==='speed'||name==='intensity')){const p=getPosition();stop(false);pausedAt=p;play()}});for(const [element,value] of [[ui.clockwise,1],[ui.counterclockwise,-1]])element.addEventListener('click',()=>{direction=value;ui.clockwise.classList.toggle('selected',value===1);ui.counterclockwise.classList.toggle('selected',value===-1);ui.clockwise.setAttribute('aria-pressed',value===1);ui.counterclockwise.setAttribute('aria-pressed',value===-1);invalidate();if(playing){const p=getPosition();stop(false);pausedAt=p;play()}});ui.export.addEventListener('click',exportAudio);

$("headerLoad").addEventListener("click",()=>ui.fileInput.click());
